name: Test Upload to Storj S3

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  upload-test-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create test file
        run: echo "This is a test file for Storj S3 upload." > test-file.txt

      - name: Upload test file to Storj S3
        uses: jakejarvis/s3-sync-action@v1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: sj://jrt1201-video/rss
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: "."
