name: Test Upload to Storj S3

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  upload-test-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Storj Uplink CLI
        run: |
          wget https://uplink-binaries.storj.io/linux/amd64/uplink
          chmod +x uplink
          ./uplink setup
          ./uplink auth --project-id ${{ secrets.storjuser }} --secret ${{ secrets.storjpass }}

      - name: Create test file
        run: echo "This is a test file for Storj S3 upload." > test-file.txt

      - name: Upload test file to Storj S3
        run: |
          ./uplink cp test-file.txt sj://jrt1201-video/rss/test-file.txt
